### ISSUE TITLE
Повторяющиеся вставки

### ISSUE THREAD

**Issue by pongo** [bespoyasov/front-not-pain#6]
По всей статье раскиданы повторяющиеся вставки текста (крупные, по центру):

> ![default](https://user-images.githubusercontent.com/142528/35671121-7b35da4c-074b-11e8-9f6e-c09e367d6a17.png)

Понимаю, если бы там была какая-то новая мысль или цитата. Но какая польза от повторения того, что я прочел пять секунд назад?

Если таким образом выделяется важная мысль, то достаточно же выделить ее полужирным, а не дублировать.

**Comment by bespoyasov** [comment]
Часто читатели не вчитываются в текст, а пробегают по нему по диагонали. 

Крупные врезки резюмируют прошедшие параграфы и выделяют важную мысль. Они помогают привлечь внимание тех, кто не вчитывается, и сориентироваться в тексте. 

Выделить полужирным недостаточно, этого не хватит, чтобы привлечь внимание при диагональном просмотре. Польза в том, чтобы даже при таком просмотре выхватить важное из статьи. 

Есть идея, как перефразировать текст до неё?

**Comment by pongo** [comment]
> Есть идея, как перефразировать текст до неё?

Перефразирование не поможет, потому что смысл фразы все равно сохранится. Значит и дублирование сохранится. Тем более, что в остальных врезках ситуация с дублированием примерно схожая. 

В принципе, такой прием довольно распространен. Но когда читаю статьи с такого рода врезками, то всегда испытываю одинаковые ощущения:

* Вижу врезку, ожидаю, что там будет что-то полезное, но оказывается, что там нет ничего нового, а просто дублирование того, что я только что прочел. Это раздражает.
* При этом игнорировать врезки я тоже не могу, вдруг в ней будет что-то новое. Но нового нет и это снова раздражает. 
* И так по кругу.

_Возможно, это какие-то мои индивидуальные заморочки..._

---

> Выделить полужирным недостаточно, этого не хватит, чтобы привлечь внимание при диагональном просмотре. 

При чтении по диагонали глаз цепляется за все что выделено, в том числе за полужирный текст. 

Конкретно в данной статье врезки сильнее привлекают внимание и на их фоне кажется, будто бы глаз не будет замечать полужирный текст при беглом просмотре. Но если врезки убрать, то глаз начнет останавливаться на полужирном.

---

> Крупные врезки резюмируют прошедшие параграфы и выделяют важную мысль.

Это так. Вот я открыл заново статью и обнаружил, что эти врезки действительно помогают вспомнить суть каждого раздела. Это очень полезно.

Может быть убрать врезки, и вместо них в конце каждого раздела сделать резюмирующий список?

> **Резюме:**
> * Знания помогают быстрее решать задачи и избегать лишней сложности.
> * Сделать нормально и не переделывать — в твоих интересах.
> * Пойми задачу и только после этого начинай её решать.
> * Не воспринимай критику, как оскорбление.

Это добавит структуру тексту. Беглый читатель увидит, что в каждом разделе есть резюме и будет читать его. Вернувшийся читатель так же сможет обратиться к резюме, чтобы освежить в памяти важное. 

Дублирование в этом случае раздражать не будет -- ведь резюме находится в отдельном месте. 

Единственно здесь теряется связь между пунктом резюме и абзацем, в котором этот пункт объясняется. Но это небольшая жертва.

**Comment by bespoyasov** [comment]
> При чтении по диагонали глаз цепляется за все что выделено, в том числе за полужирный текст.

Я пробовал ставить просто жирный, при быстрой прокрутке не работает — его просто не видно :–) 

> Может быть убрать врезки, и вместо них в конце каждого раздела сделать резюмирующий список?

Резюме будет теряться среди уже имеющихся списков в конце каждого раздела: с инструментами, статьями и книгами. Ещё один список вряд ли поможет.

> Единственно здесь теряется связь между пунктом резюме и абзацем, в котором этот пункт объясняется

В этом и проблема. Если я увидел врезку, и она меня привлекла, то мне хочется поскорее этот текст найти. Если я буду из резюме перескакивать наверх большого раздела, это будет сильнее утомлять, чем повтор какой-то мысли.

Вообще, мне не казалось, что в этих местах повторы вряд ли навредят. Это по сути выжимка из текста до неё. Повторить важное не помешает.

**Comment by andieelmes** [comment]
Можно попробовать врезки делать подытогом. То есть не повторять слово в слово, а доносить общую мысль.

Текст сверху возможно, придется переписать.

**Comment by bespoyasov** [comment]
Посмотрел, как делают ребята из Т—Ж:
<img width="1141" alt="2018-02-02 13 39 26" src="https://user-images.githubusercontent.com/9102374/35731530-98e45162-081e-11e8-9c4d-62bef360fe06.png">

Им, вроде, ок ¯\_(ツ)_/¯ 
Хотя там текста побольше перед врезкой, да.
