### ISSUE TITLE
Синтаксические ошибки

### ISSUE THREAD

**Issue by kseveru** [bespoyasov/front-not-pain#8]
"Я, может, вообще" - Я может вообще

"Не воспринимай критику, как оскорбление" - Не воспринимай критику как оскорбление

"Если какое‑то решение непонятно (вот тебе сказали подвинуть лого на пиксель вниз), сделай, а потом, спроси почему именно так." - Если какое‑то решение непонятно (вот тебе сказали подвинуть лого на пиксель вниз) -- сделай, а потом спроси, почему именно так.

"Сделаешь фигово, придётся переделывать" - Сделаешь фигово -- придётся переделывать

"Вначале думай, потом делай" - Вначале думай -- потом делай

"О вёрстке, как части проекта" - О вёрстке как части проекта

и т.п.
Вообще сделать бы какую-то штуку на сайте, чтобы можно было, увидев ошибку, выделить ее и сразу отправить вам.

**Comment by bespoyasov** [comment]
Привет! 
Спасибо за правки, поправил.

Согласен со всем, кроме: «Я, может, вообще» — здесь «может» это вводное слово.

> Вообще сделать бы какую-то штуку на сайте, чтобы можно было, увидев ошибку, выделить ее и сразу отправить вам.

Да, это было бы здорово. Есть какие-нибудь идеи на эту тему?

**Comment by kseveru** [comment]
ну, вот так сходу нашлось: http://orphus.ru/
вот тут еще обсуждают, как это сделать с помощью js+php: http://www.eomy.net/forum/interaktivnoe-ispravlenie-oshibok-na-stranitsah-saita-vt4161.html

я не знаю js, но может быть это не такая сложная штука в реализации: по определенному сочетанию клавиш высылать выделенный текст на определенную почту. Правда, вот чтобы можно было еще и исправленный вариант предложить - это сложнее, но можно и без этого.

Это просто удобно, когда сайт текстовый.

**Comment by bespoyasov** [comment]
Спасибо за ссылки!
Возьму на заметку.
